[package]
name = "advent_of_code_rust"
version = "0.0.1"
edition = "2024"

[dependencies]

[workspace]
members = [
    "aoc/util",
    "aoc/2025/*",
]

[workspace.dependencies]
anyhow = "1.0.100"
dirs = "6.0.0"
prse = "1.2.1"
